# Generated by Django 2.1 on 2018-11-11 04:38

from django.db import migrations
import pages.streamfields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_flexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', pages.streamfields.RichTextBlock())], null=True),
        ),
    ]
